### ISSUE TITLE
Script unresponsive when no Port is specified.

### ISSUE THREAD

**Issue by moooby** [algb12/UDPGeolocate#1]
Hello,

I'm having issues running the script under Windows 10.  Whenever I leave to port blank on the Config screen the script becomes unresponsive.  The config windows does not disappear and the Main windows just says: "Please wait while port is being detected..."

I turned on debug logging but this is all I see:
```
D:\UDPGeolocate (master)
λ py UDPGeolocate.py3
DEBUG:root:Host IP is 192.168.1.110
INFO:root:Windows prerequisite check passed.
DEBUG:root:Starting UDP port detection...
```
_** At this point I press Ctrl+C to stop the script **_
```
DEBUG:root:Exit handler invoked
DEBUG:root:Successfully terminated process with PID 3416
```

If I specify a random Port on the config screen things go much better, however, I never actually pull any IP data on any connections since I'm only looking at the specified port.

Any help would be greatly appreciated!

**Comment by algb12** [comment]
This is desired behaviour... well, kind of!

The script may _appear_ to become unresponsive, but in fact, if Omegle is running while the script _appears_ to be unresponsive, port detection is happening in the background...

I guess I’ll replace this pop-up with a more informative one, as this “please wait” message is merely a stop gap solution...

So, let it be “unresponsive” and start video chat... and in a few seconds, the port will be detected and data will magically appear!

Hope this helped :)
